# Generated by Django 4.0.1 on 2022-01-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_used_count', models.IntegerField()),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_title', models.CharField(max_length=200)),
                ('expenditure_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expenditure_remarks', models.TextField(blank=True, null=True)),
                ('expenditure_date', models.DateField()),
                ('belongs_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.TextField(blank=True, null=True)),
                ('receipt_pic', models.FileField(upload_to=main.models.get_receipt_filename)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_expenditure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expenditure')),
            ],
        ),
    ]
