# Generated by Django 4.0.1 on 2022-01-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_title', models.CharField(max_length=200)),
                ('reminder_desc', models.TextField(blank=True, null=True)),
                ('reminder_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reminder_due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('pic_of_bill', models.FileField(blank=True, upload_to=main.models.get_bill_filename)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('goal_desc', models.TextField(blank=True, null=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('saved_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goal_complete_date', models.DateField()),
                ('goal_set_on', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
